$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Training piple line using Random Forest Classifier

display_name: pipeline-with-classifier
experiment_name: titanic-classification

inputs:
  training_data:
    type: uri_file
    path: azureml:titanic-clean-data:2
outputs: 
  model_info_path:
    type: uri_folder


jobs:
  train_model:
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column_name: 'Survived'
    outputs:
      model_info_path: ${{parent.outputs.model_info_path}}

    environment: azureml:titanic-env:1
    compute: cpu-cluster
    code: ../components/training/
    command: >-
      python train.py
      --training_data ${{inputs.training_data}}
      --target_column_name ${{inputs.target_column_name}}
      --model_info_path ${{outputs.model_info_path}}

      
 

