$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: <enter-pipeline-description> #Training piple line using Random Forest Classifier

display_name: <enter-pipeline-name> #pipeline-with-classifier
experiment_name: <enter-experiment-name> #titanic-classification

inputs:
  training_data:
    type: uri_file
    path: <data-asset-name or data-path>
outputs: 
  model_info_path:
    type: uri_folder


jobs:
  train_model:
    inputs:
      training_data: <enter-training-data-path>   # ${{parent.inputs.training_data}}
      target_column_name:  <enter-target-column-name>    #'Survived'
    outputs:
      model_info_path: <enter-output-path>         #${{parent.outputs.model_info_path}}

    environment: <azure-env-name>     #azureml:titanic-env:1
    compute: <compute-name>  #cpu-cluster
    code:  <path-to-location> #../components/training/
    #enter script file name and parameters to be passed to the script file
    command: >-
      python train.py 
      --training_data ${{inputs.training_data}} 
      --target_column_name ${{inputs.target_column_name}}
      --model_info_path ${{outputs.model_info_path}}

      
 

