$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Training piple line using Random Forest Classifier

display_name: pipeline-with-classifier
experiment_name: titanic-classification

inputs:
  training_data:
    type: uri_file
    path: azureml:titanic-clean-data:2
  test_data:
    type: uri_file
    path: azureml:titanic-test-clean-data:1
outputs: 
  predictions_folder:
    type: uri_folder
  model_info_path:
    type: uri_folder


jobs:
  train_model:
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column_name: 'Survived'
      #model_artifacts_path: 'model'
    outputs:
      model_info_path: ${{parent.outputs.model_info_path}}

    environment: azureml:titanic-env:1
    compute: cpu-cluster
    code: ../components/training/
    command: >-
      python train.py
      --training_data ${{inputs.training_data}}
      --target_column_name ${{inputs.target_column_name}}
      --model_info_path ${{outputs.model_info_path}}
     # --model_artifacts_path ${{inputs.model_artifacts_path}}
      
  evaluate_model:
    inputs:
      test_data: ${{parent.inputs.test_data}}
      target_column_name: 'Survived'
      model_info_path: ${{parent.jobs.train_model.outputs.model_info_path}}
    outputs:
      predictions_folder: ${{parent.outputs.predictions_folder}}
      model_path:
        type: uri_folder
        mode: upload

    environment: azureml:titanic-env:1
    compute: cpu-cluster           
    code: ../components/evaluate/
    command: >-
      python evaluate.py
      --test_data ${{inputs.test_data}}
      --model_info_path ${{inputs.model_info_path}}
      --target_column_name ${{inputs.target_column_name}}
      --predictions_path ${{outputs.predictions_folder}}
      --model_path ${{outputs.model_path}}



  register_model:
    inputs:
      model_name: 'titanic_model'
      model_info_path: ${{parent.jobs.train_model.outputs.model_info_path}}

    environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:1
    compute: cpu-cluster
    code: ../components/register/
    command: >-
      python register.py
      --model_info_path ${{inputs.model_info_path}}
      --model_name ${{inputs.model_name}}   

