$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: <enter-env-name>
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: <enter-file-path>
description: <enter-env-description>